# Generated by Django 5.1.2 on 2024-12-04 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('sentence_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, unique=True)),
                ('tag_number', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('chosen_tag', models.CharField(max_length=50)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_tagger.sentence')),
                ('tag_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_tagger.tag', to_field='tag_number')),
            ],
        ),
    ]
