# Generated by Django 5.1.2 on 2024-12-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tagger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='sentence_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_number',
        ),
        migrations.AddField(
            model_name='sentence',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ners', to='pos_tagger.sentence')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ners', to='pos_tagger.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
