# Generated by Django 5.1.2 on 2024-12-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tagger', '0002_rename_tag_name_tag_name_remove_sentence_sentence_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sentence',
            new_name='Sent',
        ),
    ]
