# Generated by Django 5.1.2 on 2024-12-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tagger', '0004_rename_text_sent_sentence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sent',
            old_name='sentence',
            new_name='text',
        ),
    ]
