# Generated by Django 5.1.2 on 2024-12-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tagger', '0005_rename_sentence_sent_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sent',
            old_name='text',
            new_name='text1',
        ),
    ]
