# Generated by Django 5.1.2 on 2024-12-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tagger', '0006_rename_text_sent_text1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sent',
            old_name='text1',
            new_name='text',
        ),
    ]
