# Generated by Django 5.1.2 on 2024-12-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tagger', '0007_rename_text1_sent_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sent',
            new_name='Sentences',
        ),
    ]
