# Generated by Django 5.1.2 on 2024-12-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tagger', '0008_rename_sent_sentences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sentences',
            new_name='Sentence',
        ),
    ]
