# Generated by Django 5.1.2 on 2024-12-14 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tagger', '0009_rename_sentences_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pos',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poss', to='pos_tagger.sentence'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poss', to='pos_tagger.tag'),
        ),
    ]
