# Generated by Django 5.1.2 on 2024-12-15 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tagger', '0010_sentence_order_alter_pos_sentence_alter_pos_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='NounChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.CharField(max_length=500)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noun_chunks', to='pos_tagger.sentence')),
                ('words', models.ManyToManyField(related_name='noun_chunks', to='pos_tagger.pos')),
            ],
        ),
    ]
