# Generated by Django 5.1.2 on 2024-10-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0002_entitytype_word_delete_tagger'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagger.entitytype')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagger.word')),
            ],
        ),
    ]
