# Generated by Django 5.1.2 on 2024-12-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0002_sentence_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
