# Generated by Django 5.1.2 on 2024-12-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0003_alter_sentence_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.TextField(unique=True),
        ),
    ]
